// This file is auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.types.ts

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string
                    name: string
                    email: string
                    phone: string
                    role: 'tourist' | 'police' | 'admin'
                    photo: string | null
                    nationality: string | null
                    passport_number: string | null
                    aadhar_number: string | null
                    emergency_contacts: Json
                    safety_score: number
                    digital_id_hash: string | null
                    rfid_tag: string | null
                    badge_number: string | null
                    department: string | null
                    rank: string | null
                    is_active: boolean
                    is_verified: boolean
                    last_active: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    name: string
                    email: string
                    phone: string
                    role?: 'tourist' | 'police' | 'admin'
                    photo?: string | null
                    nationality?: string | null
                    passport_number?: string | null
                    aadhar_number?: string | null
                    emergency_contacts?: Json
                    safety_score?: number
                    digital_id_hash?: string | null
                    rfid_tag?: string | null
                    badge_number?: string | null
                    department?: string | null
                    rank?: string | null
                    is_active?: boolean
                    is_verified?: boolean
                    last_active?: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    email?: string
                    phone?: string
                    role?: 'tourist' | 'police' | 'admin'
                    photo?: string | null
                    nationality?: string | null
                    passport_number?: string | null
                    aadhar_number?: string | null
                    emergency_contacts?: Json
                    safety_score?: number
                    digital_id_hash?: string | null
                    rfid_tag?: string | null
                    badge_number?: string | null
                    department?: string | null
                    rank?: string | null
                    is_active?: boolean
                    is_verified?: boolean
                    last_active?: string
                    created_at?: string
                    updated_at?: string
                }
            }
            alerts: {
                Row: {
                    id: string
                    type: 'sos' | 'geofence' | 'anomaly' | 'health' | 'silent'
                    status: 'active' | 'responding' | 'resolved' | 'false_alarm'
                    priority: 'critical' | 'high' | 'medium' | 'low'
                    tourist_id: string
                    tourist_name: string
                    tourist_phone: string
                    location: string // GeoJSON
                    address: string | null
                    description: string | null
                    audio_evidence: string | null
                    photos: string[]
                    responding_officer_id: string | null
                    responding_officer_name: string | null
                    response_time: string | null
                    resolution_time: string | null
                    resolution_notes: string | null
                    blockchain_hash: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    type: 'sos' | 'geofence' | 'anomaly' | 'health' | 'silent'
                    status?: 'active' | 'responding' | 'resolved' | 'false_alarm'
                    priority?: 'critical' | 'high' | 'medium' | 'low'
                    tourist_id: string
                    tourist_name: string
                    tourist_phone: string
                    location: string
                    address?: string | null
                    description?: string | null
                    audio_evidence?: string | null
                    photos?: string[]
                    responding_officer_id?: string | null
                    responding_officer_name?: string | null
                    response_time?: string | null
                    resolution_time?: string | null
                    resolution_notes?: string | null
                    blockchain_hash?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    type?: 'sos' | 'geofence' | 'anomaly' | 'health' | 'silent'
                    status?: 'active' | 'responding' | 'resolved' | 'false_alarm'
                    priority?: 'critical' | 'high' | 'medium' | 'low'
                    tourist_id?: string
                    tourist_name?: string
                    tourist_phone?: string
                    location?: string
                    address?: string | null
                    description?: string | null
                    audio_evidence?: string | null
                    photos?: string[]
                    responding_officer_id?: string | null
                    responding_officer_name?: string | null
                    response_time?: string | null
                    resolution_time?: string | null
                    resolution_notes?: string | null
                    blockchain_hash?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            locations: {
                Row: {
                    id: string
                    user_id: string
                    user_type: 'tourist' | 'police'
                    location: string // GeoJSON
                    accuracy: number | null
                    altitude: number | null
                    speed: number | null
                    heading: number | null
                    in_safe_zone: boolean
                    current_zone: string | null
                    safety_level: 'safe' | 'caution' | 'danger'
                    device_id: string | null
                    battery_level: number | null
                    vitals: Json
                    timestamp: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    user_type: 'tourist' | 'police'
                    location: string
                    accuracy?: number | null
                    altitude?: number | null
                    speed?: number | null
                    heading?: number | null
                    in_safe_zone?: boolean
                    current_zone?: string | null
                    safety_level?: 'safe' | 'caution' | 'danger'
                    device_id?: string | null
                    battery_level?: number | null
                    vitals?: Json
                    timestamp?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    user_type?: 'tourist' | 'police'
                    location?: string
                    accuracy?: number | null
                    altitude?: number | null
                    speed?: number | null
                    heading?: number | null
                    in_safe_zone?: boolean
                    current_zone?: string | null
                    safety_level?: 'safe' | 'caution' | 'danger'
                    device_id?: string | null
                    battery_level?: number | null
                    vitals?: Json
                    timestamp?: string
                }
            }
            safety_scores: {
                Row: {
                    id: string
                    user_id: string
                    score: number
                    factors: Json
                    level: 'excellent' | 'good' | 'moderate' | 'low' | 'critical'
                    timestamp: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    score: number
                    factors: Json
                    level: 'excellent' | 'good' | 'moderate' | 'low' | 'critical'
                    timestamp?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    score?: number
                    factors?: Json
                    level?: 'excellent' | 'good' | 'moderate' | 'low' | 'critical'
                    timestamp?: string
                }
            }
            family_groups: {
                Row: {
                    id: string
                    name: string
                    code: string
                    created_by: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    code: string
                    created_by: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    code?: string
                    created_by?: string
                    created_at?: string
                    updated_at?: string
                }
            }
            family_members: {
                Row: {
                    id: string
                    group_id: string
                    user_id: string
                    role: 'admin' | 'member'
                    is_online: boolean
                    joined_at: string
                }
                Insert: {
                    id?: string
                    group_id: string
                    user_id: string
                    role?: 'admin' | 'member'
                    is_online?: boolean
                    joined_at?: string
                }
                Update: {
                    id?: string
                    group_id?: string
                    user_id?: string
                    role?: 'admin' | 'member'
                    is_online?: boolean
                    joined_at?: string
                }
            }
            itineraries: {
                Row: {
                    id: string
                    user_id: string
                    title: string
                    start_date: string
                    end_date: string
                    is_active: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    title: string
                    start_date: string
                    end_date: string
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    title?: string
                    start_date?: string
                    end_date?: string
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            destinations: {
                Row: {
                    id: string
                    itinerary_id: string
                    name: string
                    address: string
                    location: string // GeoJSON
                    arrival_date: string
                    departure_date: string
                    notes: string | null
                    order_index: number
                    created_at: string
                }
                Insert: {
                    id?: string
                    itinerary_id: string
                    name: string
                    address: string
                    location: string
                    arrival_date: string
                    departure_date: string
                    notes?: string | null
                    order_index?: number
                    created_at?: string
                }
                Update: {
                    id?: string
                    itinerary_id?: string
                    name?: string
                    address?: string
                    location?: string
                    arrival_date?: string
                    departure_date?: string
                    notes?: string | null
                    order_index?: number
                    created_at?: string
                }
            }
            checkpoints: {
                Row: {
                    id: string
                    destination_id: string
                    time: string
                    status: 'pending' | 'checked_in' | 'missed'
                    notes: string | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    destination_id: string
                    time: string
                    status?: 'pending' | 'checked_in' | 'missed'
                    notes?: string | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    destination_id?: string
                    time?: string
                    status?: 'pending' | 'checked_in' | 'missed'
                    notes?: string | null
                    created_at?: string
                }
            }
            efir_reports: {
                Row: {
                    id: string
                    user_id: string
                    complainant_name: string
                    complainant_phone: string
                    complainant_email: string | null
                    complainant_address: string
                    incident_type: string
                    incident_date: string
                    incident_location: string | null // GeoJSON
                    incident_address: string
                    incident_description: string
                    suspect_description: string | null
                    witnesses: string | null
                    evidence_files: string[]
                    status: 'draft' | 'submitted' | 'under_review' | 'resolved'
                    fir_number: string | null
                    assigned_officer_id: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    user_id: string
                    complainant_name: string
                    complainant_phone: string
                    complainant_email?: string | null
                    complainant_address: string
                    incident_type: string
                    incident_date: string
                    incident_location?: string | null
                    incident_address: string
                    incident_description: string
                    suspect_description?: string | null
                    witnesses?: string | null
                    evidence_files?: string[]
                    status?: 'draft' | 'submitted' | 'under_review' | 'resolved'
                    fir_number?: string | null
                    assigned_officer_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    user_id?: string
                    complainant_name?: string
                    complainant_phone?: string
                    complainant_email?: string | null
                    complainant_address?: string
                    incident_type?: string
                    incident_date?: string
                    incident_location?: string | null
                    incident_address?: string
                    incident_description?: string
                    suspect_description?: string | null
                    witnesses?: string | null
                    evidence_files?: string[]
                    status?: 'draft' | 'submitted' | 'under_review' | 'resolved'
                    fir_number?: string | null
                    assigned_officer_id?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            safe_zones: {
                Row: {
                    id: string
                    name: string
                    type: 'tourist_spot' | 'hotel' | 'hospital' | 'embassy' | 'public_place'
                    location: string // GeoJSON
                    radius: number
                    address: string | null
                    contact_phone: string | null
                    operating_hours: string | null
                    safety_rating: number | null
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    type: 'tourist_spot' | 'hotel' | 'hospital' | 'embassy' | 'public_place'
                    location: string
                    radius?: number
                    address?: string | null
                    contact_phone?: string | null
                    operating_hours?: string | null
                    safety_rating?: number | null
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    type?: 'tourist_spot' | 'hotel' | 'hospital' | 'embassy' | 'public_place'
                    location?: string
                    radius?: number
                    address?: string | null
                    contact_phone?: string | null
                    operating_hours?: string | null
                    safety_rating?: number | null
                    created_at?: string
                }
            }
            police_stations: {
                Row: {
                    id: string
                    name: string
                    location: string // GeoJSON
                    address: string
                    phone: string
                    jurisdiction: string | null
                    station_type: 'main' | 'sub' | 'outpost' | null
                    officers_count: number
                    created_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    location: string
                    address: string
                    phone: string
                    jurisdiction?: string | null
                    station_type?: 'main' | 'sub' | 'outpost' | null
                    officers_count?: number
                    created_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    location?: string
                    address?: string
                    phone?: string
                    jurisdiction?: string | null
                    station_type?: 'main' | 'sub' | 'outpost' | null
                    officers_count?: number
                    created_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
    }
}
